name: Build/release

on: push

jobs:
  release:
    if: startsWith(github.event.head_commit.message, '[CI skip]') == false
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # - name: w
      #   run: yarn add vue-i18n@9

      # - name: Commit change
      #   run: |
      #     git config --local user.email "actions@github.com"
      #     git config --local user.name "GitHub Actions"
      #     git pull origin dev
      #     git add yarn.lock
      #     git commit -m "$(date '+%Y-%m-%d %H:%M:%S')合并节点"
      # - name: Push
      #   uses:  ad-m/github-push-action@master
      #   with:
      #     branch: dev

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1.6.0
        with:
          # GitHub令牌，自动提供给动作
          # (无需在回购设置中定义此秘密)
          github_token: ${{ secrets.github_token }}

          # 如果提交被标记有版本(例如“v1.0.0”)，
          # 构建后发布应用程序
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
      - name: 自动释放
        if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "Latest-1.7.1"
          prerelease: false
          title: "build"
          files: |
            dist/*
